version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "LineBotChap"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-f9z92q7pr0wt"
s3_prefix = "LineBotChap"
region = "us-east-1"
profile = "chap"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
