AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  line-bot-chap

  Sample SAM Template for line-bot-chap


Globals:
  Function:
    Timeout: 3
    Layers:
      - arn:aws:lambda:ap-southeast-1:394922924679:layer:chatterbot-layer:1
    
Parameters:
    LineKey: 
        Type: String
        Default: 'youForgotMe'

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: trained-bot
  ReplyFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: lineBot/
      Handler: app.answer
      Runtime: python3.8
      Environment:
        Variables:
          ACCESS_TOKEN: !Ref LineKey
      Events:
        Reply:
          Type: Api 
          Properties:
            Path: /hello
            Method: post

Outputs:
  ApiEndpoint:
    Description: "API endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
