AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  line-bot-chap

  Sample SAM Template for line-bot-chap


Globals:
  Function:
    Timeout: 60
    Layers:
      - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-pymongo:4
      - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-nltk:16
      # - arn:aws:lambda:us-east-1:277726656832:layer:chatterbot:4
      - arn:aws:lambda:us-east-1:277726656832:layer:corpus-layer:2
      - arn:aws:lambda:us-east-1:277726656832:layer:chatterbot:1
      - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-spacy:28
    
Parameters:
    LineKey: 
        Type: String
        Default: 'youForgotMe'

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: trained-bot
      AccelerateConfiguration:
         AccelerationStatus: Enabled
  ReplyFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: lineBot/
      Handler: app.answer
      Runtime: python3.8
      Environment:
        Variables:
          ACCESS_TOKEN: !Ref LineKey
      Events:
        Reply:
          Type: Api 
          Properties:
            Path: /hello
            Method: post

Outputs:
  ApiEndpoint:
    Description: "API endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
