AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  line-bot-chap

  Sample SAM Template for line-bot-chap


Globals:
  Function:
    Timeout: 3

Resources:
  ReplyFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: lineBot/
      Handler: app.answer
      Runtime: python3.8
      Events:
        Reply:
          Type: Api 
          Properties:
            Path: /reply
            Method: post

Outputs:
  ApiEndpoint:
    Description: "API endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/reply/"

